# Generated by Django 3.1.2 on 2020-10-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201005_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
