# Generated by Django 3.1.2 on 2020-10-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quuestions',
            name='id',
        ),
        migrations.AddField(
            model_name='quuestions',
            name='s_no',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
        ),
    ]
