# Generated by Django 3.1.2 on 2020-10-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_quuestions_s_n_o'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
