# Generated by Django 3.1.2 on 2020-10-06 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='no_tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomarks', models.IntegerField(default=0, null=True)),
                ('nameofthetest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.topics')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.users')),
            ],
        ),
    ]
