# Generated by Django 3.1.2 on 2020-10-06 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201006_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='no_tests',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.users'),
        ),
    ]
